# Generated by Django 5.0.6 on 2024-11-18 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
        ('feedback', '0003_alter_feedbackrenter_renter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалоба на транспорт', 'verbose_name_plural': 'Жалобы на транспорт'},
        ),
        migrations.CreateModel(
            name='ComplaintForFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина жалобы')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback', verbose_name='Транспорт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на отзыв',
                'verbose_name_plural': 'Жалобы на отзывы',
                'unique_together': {('user', 'feedback')},
            },
        ),
        migrations.CreateModel(
            name='ComplaintForFeedbackRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина жалобы')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackrenter', verbose_name='Транспорт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба на отзыв',
                'verbose_name_plural': 'Жалобы на отзывы',
                'unique_together': {('user', 'feedback')},
            },
        ),
    ]
