# Generated by Django 5.0.6 on 2024-11-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complaint_options_complaintforfeedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintforfeedback',
            options={'verbose_name': 'Жалоба на отзыв арендодателя', 'verbose_name_plural': 'Жалобы на отзывы арендодателей'},
        ),
        migrations.AlterModelOptions(
            name='complaintforfeedbackrenter',
            options={'verbose_name': 'Жалоба на отзыв арендатора', 'verbose_name_plural': 'Жалобы на отзывы арендаторов'},
        ),
    ]
