# Generated by Django 5.0.6 on 2025-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_alter_complaint_user_alter_complaintforfeedback_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина жалобы'),
        ),
        migrations.AlterField(
            model_name='complaintforfeedback',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='complaintforfeedback',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина жалобы'),
        ),
        migrations.AlterField(
            model_name='complaintforfeedbackrenter',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='complaintforfeedbackrenter',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Причина жалобы'),
        ),
    ]
