# Generated by Django 5.0.6 on 2024-12-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_requestrent_deposit_cost'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID платежа в системе Тиньков')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('deposite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Депозит')),
                ('delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка')], default='pending', max_length=8, verbose_name='Статус платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('request_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='chat.requestrent', verbose_name='Заявка на аренду')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.DeleteModel(
            name='PaymentSetting',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
