# Generated by Django 5.0.6 on 2024-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_delete_paymentsetting_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=255, verbose_name='ID платежа в системе Тиньков'),
        ),
    ]
