# Generated by Django 5.0.6 on 2024-12-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0013_usedpromocode'),
        ('payment', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.promocode', verbose_name='Примененный промокод'),
        ),
    ]
