# Generated by Django 5.0.6 on 2024-12-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0016_remove_organization_contacts_contact_organization'),
        ('payment', '0004_payment_discount_amount_payment_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.influencer', verbose_name='Партнер'),
        ),
    ]
