# Generated by Django 5.0.6 on 2025-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
