# Generated by Django 5.0.6 on 2025-02-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('canceled', 'Отменен')], default='pending', max_length=8, verbose_name='Статус платежа'),
        ),
    ]
