# Generated by Django 5.0.6 on 2024-08-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='Реферальный код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инфлюенсер',
                'verbose_name_plural': 'Инфлюенсеры',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50, verbose_name='Название канала')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество регистраций')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='influencer.influencer', verbose_name='Инфлюенсер')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
            },
        ),
    ]
