# Generated by Django 5.0.6 on 2024-11-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_city_alter_franchise_city'),
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('social', models.CharField(max_length=250, verbose_name='Сайт или соцсеть')),
                ('description', models.CharField(max_length=250, verbose_name='Чем вы занимаетесь')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franchise.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заявка на создание инфлюенсера',
                'verbose_name_plural': 'Заявки на создание инфлюенсеров',
            },
        ),
    ]
