# Generated by Django 5.0.6 on 2024-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_influencerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerrequest',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
    ]
