# Generated by Django 5.0.6 on 2024-12-16 08:12

import django.db.models.deletion
import influencer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_alter_influencerrequest_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100, verbose_name='Название канала')),
                ('referral_link', models.URLField(blank=True, verbose_name='Реферальная ссылка')),
                ('qr_code_image', models.ImageField(blank=True, upload_to=influencer.models.qr_code_upload_path, verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='influencer.influencer', verbose_name='Инфлюенсер')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
            },
        ),
    ]
