# Generated by Django 5.0.6 on 2024-12-18 09:41

import django.db.models.deletion
import influencer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('account_number', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('account_owner', models.CharField(max_length=255, verbose_name='ФИО владельца счета')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Эл.почта')], max_length=10, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Серия и номер')),
                ('photo', models.ImageField(upload_to=influencer.models.upload_renter_document, verbose_name='Фото')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус проверки')),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='influencer.influencer', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'Паспортные данные',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('bank_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.bankdetails', verbose_name='Банковские реквизиты')),
                ('contacts', models.ManyToManyField(blank=True, to='influencer.contact', verbose_name='Контакты')),
            ],
        ),
        migrations.AddField(
            model_name='influencer',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.organization', verbose_name='Организация'),
        ),
    ]
