# Generated by Django 5.0.6 on 2024-12-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_bankdetails_contact_influencerdocuments_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerdocuments',
            name='influencer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='influencer.influencer', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='influencerdocuments',
            name='number',
            field=models.CharField(verbose_name='Серия и номер'),
        ),
    ]
