# Generated by Django 5.0.6 on 2024-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_alter_influencer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='commission',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
