# Generated by Django 5.0.6 on 2024-12-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_influencer_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество регистраций'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('percent', models.BooleanField(verbose_name='Процент')),
                ('cash', models.BooleanField(verbose_name='Бонусные рубли')),
                ('total', models.PositiveIntegerField(verbose_name='Колличество')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество регистраций')),
                ('influecer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='influencer.influencer', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
