# Generated by Django 5.0.6 on 2024-12-19 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_qrcode_count_promocode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='RegistrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('referral', 'Реферальная ссылка'), ('qr_code', 'QR-код'), ('promo', 'Промокод')], max_length=20, verbose_name='Тип источника')),
                ('source_details', models.CharField(blank=True, max_length=100, verbose_name='Детали источника (ссылка, qr код и т.д.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='influencer.influencer', verbose_name='Инфлюенсер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_source', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
