# Generated by Django 5.0.6 on 2024-12-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0010_alter_promocode_title_registrationsource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='influecer',
            new_name='influencer',
        ),
    ]
