# Generated by Django 5.0.6 on 2024-12-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0011_rename_influecer_promocode_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
