# Generated by Django 5.0.6 on 2024-12-20 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0012_promocode_created_at_referrallink_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата применения')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='influencer.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'unique_together': {('user', 'promo_code')},
            },
        ),
    ]
