# Generated by Django 5.0.6 on 2024-12-25 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0014_change_type_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer', to='influencer.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('percent', 'Процент'), ('cash', 'Бонусные рубли')], default='percent', max_length=10, verbose_name='Тип промокода'),
        ),
    ]
