# Generated by Django 5.0.6 on 2024-12-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0015_alter_influencer_organization_alter_promocode_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='influencer.organization'),
        ),
    ]
