# Generated by Django 5.0.6 on 2025-01-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0016_remove_organization_contacts_contact_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Банковские данные инфлюенсера', 'verbose_name_plural': 'Банковские данные инфлюенсеров'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты инфлюенсера', 'verbose_name_plural': 'Контакты инфлюенсеров'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация инфлюенсера', 'verbose_name_plural': 'Организации инфлюенсеров'},
        ),
        migrations.AlterModelOptions(
            name='registrationsource',
            options={'verbose_name': 'Информация о реферальной регистрации', 'verbose_name_plural': 'Информация о реферальной регистрации'},
        ),
        migrations.AlterModelOptions(
            name='usedpromocode',
            options={'verbose_name': 'Использованный промокод', 'verbose_name_plural': 'Использованные промокоды'},
        ),
    ]
