# Generated by Django 5.0.6 on 2025-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0017_alter_bankdetails_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='email_1',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта №1'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='email_2',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта №2'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='telephone_1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон №1'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон №2'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
