# Generated by Django 5.0.6 on 2025-02-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0018_influencer_email_1_influencer_email_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWithdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('in_progress', 'В процессе'), ('denied', 'Отказано')], default='In_progress', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('denied_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='influencer.influencer', verbose_name='Инфлюенсер')),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств',
                'verbose_name_plural': 'Заявки на вывод средств',
            },
        ),
    ]
