# Generated by Django 5.0.6 on 2025-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0019_requestwithdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Счет'),
        ),
    ]
