# Generated by Django 5.0.6 on 2024-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
