# Generated by Django 5.0.6 on 2024-08-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='RequestFranchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл. почта')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заявка на франшизу',
                'verbose_name_plural': 'Заявки на франшизы',
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя компании')),
                ('unn', models.CharField(max_length=12, unique=True, verbose_name='УНН')),
                ('date_register', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл. почта')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('commission', models.PositiveIntegerField(default=3, verbose_name='Комиссия')),
                ('total_vehicles', models.PositiveIntegerField(default=0, verbose_name='Общее количество транспортных средств')),
                ('categories', models.ManyToManyField(related_name='franchises', to='franchise.category', verbose_name='Категории')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
            },
        ),
        migrations.CreateModel(
            name='VehiclePark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название автопарка')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_parks', to='franchise.franchise', verbose_name='Франшиза')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_parks', to=settings.AUTH_USER_MODEL, verbose_name='Автопарк')),
            ],
            options={
                'verbose_name': 'Автопарк',
                'verbose_name_plural': 'Автопарки',
            },
        ),
    ]
