# Generated by Django 5.0.6 on 2025-01-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_lessor_franchise'),
        ('franchise', '0003_alter_franchise_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAddLessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_consideration', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='on_consideration', verbose_name='Статус')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_lessor', to='franchise.franchise', verbose_name='Франшиза')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_lessor', to='app.lessor', verbose_name='Арендодатель')),
            ],
            options={
                'unique_together': {('franchise', 'lessor')},
            },
        ),
    ]
