# Generated by Django 5.0.6 on 2025-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0005_alter_franchise_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='account_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО владельца счета'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='email_2',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта №2'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон №2'),
        ),
    ]
