# Generated by Django 5.0.6 on 2025-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0006_franchise_account_number_franchise_account_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='telephone',
        ),
        migrations.AddField(
            model_name='franchise',
            name='email_1',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Почта №1'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='telephone_1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон №1'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон №2'),
        ),
    ]
