# Generated by Django 5.0.6 on 2025-02-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0007_remove_franchise_email_remove_franchise_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='date_register',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
