# Generated by Django 5.0.6 on 2024-11-17 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_telephone'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв о транспорте', 'verbose_name_plural': 'Отзывы о отранспорте'},
        ),
        migrations.CreateModel(
            name='FeedbackRenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='app.renter', verbose_name='Арендодатель, которому оставлен отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, оставивший отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв о пользователе',
                'verbose_name_plural': 'Отзывы о пользователях',
                'unique_together': {('user', 'renter')},
            },
        ),
    ]
