# Generated by Django 5.0.6 on 2025-06-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_user_alter_feedbackrenter_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(max_length=255, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedbackrenter',
            name='content',
            field=models.CharField(max_length=255, null=True, verbose_name='Отзыв'),
        ),
    ]
