# Generated by Django 5.0.6 on 2025-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_content_alter_feedbackrenter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedbackrenter',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзыв'),
        ),
    ]
