# Generated by Django 5.0.6 on 2024-08-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Тема')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Тема чата с техподдержкой',
                'verbose_name_plural': 'Темы чатов с техподдержкой',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='ChatSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_support', to='chat.topicsupport', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Чат с техподдержкой',
                'verbose_name_plural': 'Чаты с техподдержкой',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('object_id', models.PositiveIntegerField(verbose_name='id транспорта')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('auto', 'bike', 'ship', 'helicopter', 'specialtechnic')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип транспорта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/chat_files/', verbose_name='Файл')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/support_chat_files/', verbose_name='Файл')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('support_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_support', to='chat.chatsupport', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Сообщение чата техподдержки',
                'verbose_name_plural': 'Сообщения чата техподдержки',
            },
        ),
        migrations.CreateModel(
            name='RequestRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'Принять'), ('denied', 'Отказать'), ('unknown', 'Не рассмотренно')], default='unknown', max_length=7, verbose_name='Статус')),
                ('object_id', models.PositiveIntegerField(verbose_name='id транспорта')),
                ('start_date', models.DateField(verbose_name='Начало аренды')),
                ('end_date', models.DateField(verbose_name='Конец аренды')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('deposit_paid', models.BooleanField(default=False)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('auto', 'bike', 'ship', 'helicopter', 'specialtechnic')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип транспорта')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_rent_organized_trips', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка на аренду',
                'verbose_name_plural': 'Заявки на аренду',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'Текущая поездка'), ('finished', 'Завершить'), ('canceled', 'Отменить')], default='current', max_length=8, verbose_name='Статус')),
                ('object_id', models.PositiveIntegerField(verbose_name='id транспорта')),
                ('start_date', models.DateField(verbose_name='Начало поездки')),
                ('end_date', models.DateField(verbose_name='Конец поездки')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость аренды')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('auto', 'bike', 'ship', 'helicopter', 'specialtechnic')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип транспорта')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_organized_trips', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.trip', verbose_name='Поездка'),
        ),
    ]
