# Generated by Django 5.0.6 on 2024-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
