# Generated by Django 5.0.6 on 2024-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_feedback_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
