# Generated by Django 5.0.6 on 2024-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_requestrent_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания аренды'),
        ),
        migrations.AddField(
            model_name='requestrent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала аренды'),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания аренды'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала аренды'),
        ),
    ]
