# Generated by Django 5.0.6 on 2024-10-31 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_requestrent_end_time_requestrent_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='trip',
        ),
        migrations.AddField(
            model_name='chat',
            name='request_rent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.requestrent', verbose_name='Заявка на аренду'),
        ),
        migrations.AddField(
            model_name='requestrent',
            name='deposit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Залог'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец аренды'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало аренды'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='status',
            field=models.CharField(choices=[('accept', 'Принять'), ('denied', 'Отказать'), ('unknown', 'Не рассмотрено')], default='unknown', max_length=7, verbose_name='Статус'),
        ),
    ]
