# Generated by Django 5.0.6 on 2024-10-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_trip_chat_request_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrent',
            name='deposit_paid',
        ),
    ]
