# Generated by Django 5.0.6 on 2024-11-02 07:25

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_requestrent_deposit_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='request_rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.requestrent', verbose_name='Заявка на аренду'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.file_chat_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='status',
            field=models.CharField(choices=[('accept', 'Принять'), ('denied', 'Отказать'), ('unknown', 'Не рассмотрено')], default='unknown', max_length=8, verbose_name='Статус'),
        ),
    ]
