# Generated by Django 5.0.6 on 2024-11-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_chat_request_rent_alter_message_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.chat'),
        ),
    ]
