# Generated by Django 5.0.6 on 2024-11-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_trip_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
