# Generated by Django 5.0.6 on 2024-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesupport',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('current', 'Текущая поездка'), ('started', 'В процессе'), ('finished', 'Завершить'), ('canceled', 'Отменить')], default='current', max_length=8, verbose_name='Статус'),
        ),
    ]
