# Generated by Django 5.0.6 on 2024-11-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_messagesupport_deleted_alter_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsupport',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chatsupport',
            name='topic',
        ),
        migrations.AlterField(
            model_name='chatsupport',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_chats', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='IssueSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_chat', to='chat.chatsupport', verbose_name='Чат техподдержки')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_support', to='chat.topicsupport', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Обращение в техподдержку',
                'verbose_name_plural': 'Обращения в техподдержку',
            },
        ),
    ]
