# Generated by Django 5.0.6 on 2024-11-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_chatsupport_participants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicsupport',
            options={'ordering': ['-count'], 'verbose_name': 'Тема чата с техподдержкой', 'verbose_name_plural': 'Темы чатов с техподдержкой'},
        ),
    ]
