# Generated by Django 5.0.6 on 2024-11-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_topicsupport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='request_rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.requestrent', verbose_name='Заявка на аренду'),
        ),
    ]
