# Generated by Django 5.0.6 on 2024-11-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_chat_request_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chat'),
        ),
    ]
