# Generated by Django 5.0.6 on 2024-11-26 16:25

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_trip_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesupport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.file_support_chat_upload_to, verbose_name='Файл'),
        ),
    ]
