# Generated by Django 5.0.6 on 2024-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_messagesupport_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesupport',
            old_name='support_chat',
            new_name='chat',
        ),
    ]
