# Generated by Django 5.0.6 on 2024-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_rename_support_chat_messagesupport_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='on_request',
            field=models.BooleanField(blank=True, null=True, verbose_name='Заявка по запросу'),
        ),
    ]
