# Generated by Django 5.0.6 on 2024-12-12 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_requestrent_on_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='request_rent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.requestrent', verbose_name='Заявка на аренду'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='requestrent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_rent_organized_trips', to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chat'),
        ),
    ]
