# Generated by Django 5.0.6 on 2024-12-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_requestrent_is_deleted_alter_chat_request_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='denied_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
    ]
