# Generated by Django 5.0.6 on 2024-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_requestrent_denied_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrent',
            name='deposit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Депозит'),
        ),
    ]
