# Generated by Django 5.0.6 on 2024-12-25 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_requestrent_deposit_cost'),
        ('influencer', '0015_alter_influencer_organization_alter_promocode_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrent',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Использованные бонусные рубли'),
        ),
        migrations.AddField(
            model_name='requestrent',
            name='promocode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.promocode', verbose_name='Активный промокод'),
        ),
    ]
