# Generated by Django 5.0.6 on 2025-01-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_requestrent_bonus_requestrent_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrent',
            name='denied_reason',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Причина отказа'),
        ),
    ]
