# Generated by Django 5.0.6 on 2025-02-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_requestrent_denied_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='request_rent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='chat.requestrent', verbose_name='Заявка на аренду'),
        ),
    ]
