# Generated by Django 5.0.6 on 2025-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_alter_chat_request_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
