# Generated by Django 5.0.6 on 2025-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_message_is_read_messagesupport_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
        migrations.AddField(
            model_name='messagesupport',
            name='language',
            field=models.CharField(default='ru', max_length=10),
        ),
    ]
