# Generated by Django 5.0.6 on 2025-07-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_requestrent_amount_trip_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestrent',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='amount',
        ),
    ]
