# Generated by Django 5.0.6 on 2025-07-28 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_remove_requestrent_amount_remove_trip_amount'),
        ('influencer', '0020_influencer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrent',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_rents', to='influencer.promocode', verbose_name='Активный промокод'),
        ),
    ]
