# Generated by Django 5.0.6 on 2024-08-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
        ('influencer', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='vehicle.vehicle', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='renter',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renters', to='influencer.influencer', verbose_name='Инфлюенсер'),
        ),
        migrations.AddField(
            model_name='renter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='app.renter'),
        ),
        migrations.AddField(
            model_name='renterdocuments',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_documents', to='app.renter'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'renter')},
        ),
    ]
