# Generated by Django 5.0.6 on 2024-09-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
        ('vehicle', '0002_vehicle_last_update_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название списка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_lists', to='app.renter')),
                ('vehicles', models.ManyToManyField(related_name='in_favorite_lists', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Список избранного',
                'verbose_name_plural': 'Списки избранного',
                'unique_together': {('renter', 'name')},
            },
        ),
    ]
