# Generated by Django 5.0.6 on 2024-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_favoritelist'),
        ('vehicle', '0002_vehicle_last_update_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='in_favorite_lists', to='vehicle.vehicle'),
        ),
    ]
