# Generated by Django 5.0.6 on 2024-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_favoritelist_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'Английский'), ('es', 'Испанский'), ('fr', 'Французский'), ('de', 'Немецкий'), ('zh', 'Китайский')], max_length=2, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('RUB', 'рубль'), ('EUR', 'евро'), ('USD', 'доллар'), ('GBP', 'фунт стерлингов'), ('JPY', 'йена'), ('CNY', 'юань')], max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
