# Generated by Django 5.0.6 on 2024-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_currency_language_alter_user_push_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterdocuments',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус проверки'),
        ),
    ]
