# Generated by Django 5.0.6 on 2024-09-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_renterdocuments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.language', verbose_name='Язык'),
        ),
    ]
