# Generated by Django 5.0.6 on 2024-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_currency_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone_verified',
            field=models.BooleanField(default=False, verbose_name='Телефон подтвержден'),
        ),
    ]
