# Generated by Django 5.0.6 on 2024-10-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_telephone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
