# Generated by Django 5.0.6 on 2024-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterdocuments',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='renterdocuments',
            name='title',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('license', 'Права')], max_length=30, verbose_name='Вид документа'),
        ),
    ]
