# Generated by Django 5.0.6 on 2024-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_renterdocuments_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Комиссия'),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='count_trip',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество поездок'),
        ),
    ]
