# Generated by Django 5.0.6 on 2024-11-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_lessor_commission_alter_lessor_count_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='favorite',
        ),
    ]
