# Generated by Django 5.0.6 on 2024-12-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_telephone'),
        ('influencer', '0007_alter_influencer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessors', to='influencer.influencer', verbose_name='Инфлюенсер'),
        ),
    ]
