# Generated by Django 5.0.6 on 2024-12-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_lessor_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='bonus_account',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Бонусный счет'),
        ),
    ]
