# Generated by Django 5.0.6 on 2025-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_renter_bonus_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Email уведомления'),
        ),
    ]
