# Generated by Django 5.0.6 on 2025-01-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_email_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessor',
            name='franchise',
        ),
    ]
