# Generated by Django 5.0.6 on 2025-01-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_lessor_franchise'),
        ('franchise', '0003_alter_franchise_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessor',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessors', to='franchise.franchise', verbose_name='Франшиза'),
        ),
    ]
