# Generated by Django 5.0.6 on 2025-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_lessor_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('web', 'Веб'), ('android', 'Андроид'), ('ios', 'ios'), ('unknown', 'Неизвестно')], null=True, verbose_name='Платформа'),
        ),
    ]
