# Generated by Django 5.0.6 on 2025-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_user_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='platform',
            field=models.CharField(blank=True, choices=[('web', 'Веб'), ('android', 'Андроид'), ('ios', 'ios'), ('unknown', 'Неизвестно')], null=True, verbose_name='Платформа'),
        ),
    ]
