# Generated by Django 5.0.6 on 2025-05-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessor',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Комиссия'),
        ),
    ]
