# Generated by Django 5.0.6 on 2024-09-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0002_city_alter_franchise_city'),
        ('vehicle', '0002_vehicle_last_update_vehicle_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='franchise.city', verbose_name='Город'),
        ),
    ]
