# Generated by Django 5.0.6 on 2024-09-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='AutoFuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Вид топлива')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
            },
        ),
        migrations.CreateModel(
            name='AutoTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.CreateModel(
            name='BikeTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.AlterField(
            model_name='auto',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.autobodytype', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.autofueltype', verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.autotransmission', verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.biketransmission', verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='vehicle_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicleclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='vehicle_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicleclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='helicopter',
            name='vehicle_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicleclass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='vehicle_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicleclass', verbose_name='Класс'),
        ),
    ]
