# Generated by Django 5.0.6 on 2024-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_autobodytype_autofueltype_autotransmission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autobodytype',
            options={'verbose_name': 'Авто, тип кузова', 'verbose_name_plural': 'Авто, типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='autofueltype',
            options={'verbose_name': 'Авто, вид топлива', 'verbose_name_plural': 'Авто, виды топлива'},
        ),
        migrations.AlterModelOptions(
            name='autotransmission',
            options={'verbose_name': 'Авто, коробка передач', 'verbose_name_plural': 'Авто, коробки передач'},
        ),
        migrations.AddField(
            model_name='autobodytype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='autofueltype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='autotransmission',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicleclass',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='autobodytype',
            name='title',
            field=models.CharField(max_length=12, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='autotransmission',
            name='title',
            field=models.CharField(max_length=12, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='title',
            field=models.CharField(max_length=12, verbose_name='Вид топлива'),
        ),
    ]
