# Generated by Django 5.0.6 on 2024-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_autobodytype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleclass',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='title',
            field=models.CharField(max_length=12, verbose_name='Класс'),
        ),
    ]
