# Generated by Django 5.0.6 on 2024-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicleclass_slug_alter_vehicleclass_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autofeaturesadditionally',
            options={'verbose_name': 'Автомобиль, дополнительная особенность', 'verbose_name_plural': 'Автомобиль, дополнительные особенности'},
        ),
        migrations.AlterModelOptions(
            name='bikefeaturesadditionally',
            options={'verbose_name': 'Мотоцикл, Дополнительная особенность', 'verbose_name_plural': 'Мотоцикл, Дополнительные особенности'},
        ),
        migrations.AlterModelOptions(
            name='featuresequipment',
            options={'verbose_name': 'Судно, оборудование', 'verbose_name_plural': 'Судно, оборудование'},
        ),
        migrations.AlterModelOptions(
            name='featuresforchildren',
            options={'verbose_name': 'Авто, для детей', 'verbose_name_plural': 'Авто, для детей'},
        ),
        migrations.AlterModelOptions(
            name='shipfeaturesadditionally',
            options={'verbose_name': 'Судно, дополнительная особенность', 'verbose_name_plural': 'Судно, дополнительные особенности'},
        ),
        migrations.AlterField(
            model_name='autobodytype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='autofueltype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='autotransmission',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='vehicleclass',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Класс'),
        ),
    ]
