# Generated by Django 5.0.6 on 2024-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_autofeaturesadditionally_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobodytype',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='autobodytype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='autofueltype',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='autotransmission',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='autotransmission',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Коробка передач'),
        ),
    ]
