# Generated by Django 5.0.6 on 2024-09-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_autobodytype_slug_alter_autobodytype_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autobodytype',
            options={'verbose_name': 'Автомобиль, тип кузова', 'verbose_name_plural': 'Автомобиль, типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='autofueltype',
            options={'verbose_name': 'Автомобиль, вид топлива', 'verbose_name_plural': 'Автомобиль, виды топлива'},
        ),
        migrations.AlterModelOptions(
            name='autotransmission',
            options={'verbose_name': 'Автомобиль, коробка передач', 'verbose_name_plural': 'Автомобиль, коробки передач'},
        ),
        migrations.AlterModelOptions(
            name='biketransmission',
            options={'verbose_name': 'Мотоцикл, коробка передач', 'verbose_name_plural': 'Мотоцикл, коробки передач'},
        ),
        migrations.AlterModelOptions(
            name='featuresforchildren',
            options={'verbose_name': 'Автомобиль, для детей', 'verbose_name_plural': 'Автомобиль, для детей'},
        ),
        migrations.AddField(
            model_name='biketransmission',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
    ]
