# Generated by Django 5.0.6 on 2024-10-17 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_autobodytype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentprice',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Скидка'),
        ),
    ]
