# Generated by Django 5.0.6 on 2024-10-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_rentprice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingupdatelog',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingupdatelog',
            name='cleanliness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingupdatelog',
            name='communication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingupdatelog',
            name='convenience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratingupdatelog',
            name='maintenance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
