# Generated by Django 5.0.6 on 2024-10-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_ratingupdatelog_accuracy_ratingupdatelog_cleanliness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='on_request',
            field=models.BooleanField(default=False, verbose_name='По запросу'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
