# Generated by Django 5.0.6 on 2024-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_availability_on_request_alter_availability_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentprice',
            name='commission',
        ),
        migrations.AlterField(
            model_name='rentprice',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='ИТОГО'),
        ),
    ]
