# Generated by Django 5.0.6 on 2024-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_remove_rentprice_commission_alter_rentprice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('auto', 'Автомобиль'), ('bike', 'Мотоцикл'), ('ship', 'Судно'), ('helicopter', 'Вертолет'), ('special_technic', 'Спецтехника')], max_length=20, null=True, verbose_name='Тип транспорта'),
        ),
    ]
