# Generated by Django 5.0.6 on 2024-11-10 15:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_alter_vehiclemodel_brand_alter_vehiclemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vehiclebrand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vehicle_veh_search__696aca_gin'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='vehicle_veh_search__7cb014_gin'),
        ),
    ]
