# Generated by Django 5.0.6 on 2024-11-10 16:31

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_vehiclebrand_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclebrand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='vehicle_brand_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='vehicle_model_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
