# Generated by Django 5.0.6 on 2024-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_vehiclebrand_vehicle_brand_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='count_trip',
            field=models.IntegerField(default=0, verbose_name='Количество поездок'),
        ),
    ]
