# Generated by Django 5.0.6 on 2025-01-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_vehicle_count_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingupdatelog',
            options={'verbose_name': 'Лог обновления рейтинга транспорта', 'verbose_name_plural': 'Логи обновления рейтингов транспорта'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
    ]
