# Generated by Django 5.0.6 on 2025-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_alter_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ensurance',
            field=models.CharField(max_length=255, verbose_name='Страховка'),
        ),
    ]
