# Generated by Django 5.0.6 on 2025-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_alter_vehicle_ensurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclephoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
