# Generated by Django 5.0.6 on 2025-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_vehiclephoto_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('auto', 'Автомобили'), ('bike', 'Мотоциклы'), ('helicopter', 'Вертолёты'), ('ship', 'Корабли'), ('specialtechnic', 'Спецтехника')], max_length=20, unique=True, verbose_name='Тип транспорта')),
            ],
            options={
                'verbose_name': 'Категория транспорта',
                'verbose_name_plural': 'Категории транспорта',
            },
        ),
        migrations.AlterModelOptions(
            name='vehiclephoto',
            options={'ordering': ['order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='transport_categories',
            field=models.ManyToManyField(related_name='brands', to='vehicle.vehiclecategory', verbose_name='Категории транспорта'),
        ),
    ]
