# Generated by Django 5.0.6 on 2025-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_vehiclecategory_alter_vehiclephoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(choices=[('auto', 'Автомобили'), ('bike', 'Мотоциклы'), ('helicopter', 'Вертолёты'), ('ship', 'Судна'), ('special_technic', 'Спецтехника')], max_length=20, unique=True, verbose_name='Тип транспорта'),
        ),
    ]
