# Generated by Django 5.0.6 on 2025-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0024_alter_vehiclecategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeFeaturesFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Мотоцикл, функция',
                'verbose_name_plural': 'Мотоцикл, функции',
            },
        ),
        migrations.CreateModel(
            name='ShipFeaturesFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Судно, функция',
                'verbose_name_plural': 'Судно, функции',
            },
        ),
        migrations.RenameModel(
            old_name='VehicleFeaturesFunctions',
            new_name='AutoFeaturesFunctions',
        ),
        migrations.AlterModelOptions(
            name='autofeaturesfunctions',
            options={'verbose_name': 'Автомобиль, функция', 'verbose_name_plural': 'Автомобиль, функции'},
        ),
        migrations.AlterField(
            model_name='bike',
            name='features_functions',
            field=models.ManyToManyField(related_name='bike', to='vehicle.bikefeaturesfunctions', verbose_name='Функции'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='features_functions',
            field=models.ManyToManyField(related_name='ship', to='vehicle.shipfeaturesfunctions', verbose_name='Функции'),
        ),
    ]
