# Generated by Django 5.0.6 on 2025-04-29 17:38

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0025_bikefeaturesfunctions_shipfeaturesfunctions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclephoto',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=vehicle.models.vehicle_photo_upload_to, verbose_name='Фото'),
        ),
    ]
