# Generated by Django 5.0.6 on 2025-05-08 08:40

import django.db.models.deletion
from django.db import migrations, models


def create_default_bike_body_type(apps, schema_editor):
    BikeBodyType = apps.get_model('vehicle', 'BikeBodyType')
    Bike = apps.get_model('vehicle', 'Bike')
    scooter = BikeBodyType.objects.create(title='Скутер', slug='skuter')
    Bike.objects.all().update(body_type=scooter)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0026_alter_vehiclephoto_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип мотоцикла')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Мотоцикл, тип',
                'verbose_name_plural': 'Мотоцикл, типы',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.bikebodytype', verbose_name='Тип мотоцикла'),
        ),
        migrations.RunPython(create_default_bike_body_type),
    ]
