# Generated by Django 5.0.6 on 2025-05-08 09:11

import django.db.models.deletion
from django.db import migrations, models

def create_default_types(apps, schema_editor):
    ShipType = apps.get_model('vehicle', 'ShipType')
    TechnicType = apps.get_model('vehicle', 'TechnicType')
    Ship = apps.get_model('vehicle', 'Ship')
    SpecialTechnic = apps.get_model('vehicle', 'SpecialTechnic')

    yacht_type = ShipType.objects.create(title='Яхта', slug='yahta')
    Ship.objects.all().update(type_ship=yacht_type)

    bulldozer_type = TechnicType.objects.create(title='Бульдозер', slug='buldozer')
    SpecialTechnic.objects.all().update(type_technic=bulldozer_type)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0027_bikebodytype_bike_body_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип мотоцикла')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Судно, тип',
                'verbose_name_plural': 'Судно, типы',
            },
        ),
        migrations.CreateModel(
            name='TechnicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип мотоцикла')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Спец техника, тип',
                'verbose_name_plural': 'Спец техника, типы',
            },
        ),
        migrations.AlterField(
            model_name='ship',
            name='type_ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.shiptype', verbose_name='Тип судна'),
        ),
        migrations.AlterField(
            model_name='specialtechnic',
            name='type_technic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.technictype', verbose_name='Тип судна'),
        ),
        migrations.RunPython(create_default_types),
    ]
