# Generated by Django 5.0.6 on 2025-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0028_shiptype_technictype_alter_ship_type_ship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Средний рейтинг'),
        ),
    ]
