# Generated by Django 5.0.6 on 2025-07-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0029_vehicle_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentprice',
            name='name',
            field=models.CharField(choices=[('hour', 'Час'), ('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], max_length=5, verbose_name='Период'),
        ),
    ]
