# Generated by Django 5.0.6 on 2025-07-30 13:06

import django.utils.timezone
from django.db import migrations, models


def set_created_at(apps, schema_editor):
    Vehicle = apps.get_model('vehicle', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        vehicle.created_at = vehicle.last_update or django.utils.timezone.now()
        vehicle.save(update_fields=['created_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0030_alter_rentprice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.RunPython(set_created_at),
    ]
