# Generated by Django 5.0.6 on 2025-01-07 12:58

import django.db.models.deletion
import manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(verbose_name='Серия и номер')),
                ('photo', models.ImageField(upload_to=manager.models.upload_manager_document, verbose_name='Фото')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_document', to='manager.manager')),
            ],
            options={
                'verbose_name': 'Паспортные данные',
                'verbose_name_plural': 'Паспортные данные',
            },
        ),
        migrations.CreateModel(
            name='ManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('permission_type', models.CharField(choices=[('read', 'Чтение'), ('edit', 'Редактирование'), ('delete', 'Удаление')], max_length=50, verbose_name='Тип доступа')),
                ('is_global', models.BooleanField(default=False, verbose_name='Глобальный доступ')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='manager.manager')),
            ],
            options={
                'verbose_name': 'Права менеджера',
                'verbose_name_plural': 'Права менеджеров',
                'unique_together': {('manager', 'content_type', 'object_id', 'permission_type', 'is_global')},
            },
        ),
    ]
