# Generated by Django 5.0.6 on 2025-01-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterField(
            model_name='managerdocuments',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_document', to='manager.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='managerdocuments',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Серия и номер'),
        ),
        migrations.AlterField(
            model_name='managerpermission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип модели'),
        ),
        migrations.AlterField(
            model_name='managerpermission',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
    ]
