# Generated by Django 5.0.6 on 2025-01-08 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_options_alter_managerdocuments_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='password_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения пароля'),
        ),
    ]
