# Generated by Django 5.0.6 on 2025-01-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0004_requestaddlessor'),
        ('manager', '0003_manager_password_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='franchise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='franchise.franchise', verbose_name='Франшиза'),
        ),
    ]
