# Generated by Django 5.0.6 on 2025-07-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_change_franchise_to_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerPermission',
        ),
    ]
