# Generated by Django 5.0.6 on 2025-07-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_delete_managerpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='permission',
            field=models.CharField(choices=[('read', 'Чтение'), ('edit', 'Редактирование'), ('delete', 'Удаление')], default='read', max_length=10, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='name',
            field=models.CharField(choices=[('lessors', 'Арендодатели'), ('departments', 'Подразделения'), ('partnership', 'Партнерская программа'), ('staff', 'Персонал'), ('rent_orders', 'Аренда и заказы'), ('rent_journal', 'Аренда журнал'), ('chats', 'Чаты'), ('reports', 'Отчеты')], max_length=50, verbose_name='Тип доступа'),
        ),
        migrations.AlterUniqueTogether(
            name='accesstype',
            unique_together={('name', 'permission')},
        ),
    ]
