# Generated by Django 5.0.6 on 2025-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0010_franchisedocuments'),
        ('manager', '0009_accesstype_permission_alter_accesstype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='city',
        ),
        migrations.AddField(
            model_name='manager',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, related_name='managers', to='franchise.city', verbose_name='Города'),
        ),
    ]
