# Generated by Django 5.0.6 on 2025-07-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_manager_city_manager_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstype',
            name='name',
            field=models.CharField(choices=[('vehicles', 'Транспорт'), ('lessors', 'Арендодатели'), ('departments', 'Подразделения'), ('partnership', 'Партнерская программа'), ('staff', 'Персонал'), ('rent_orders', 'Аренда и заказы'), ('rent_journal', 'Аренда журнал'), ('chats', 'Чаты'), ('reports', 'Отчеты')], max_length=50, verbose_name='Тип доступа'),
        ),
    ]
